#!/usr/bin/env bash
# This script displays "Holberton School" 10 times and says "Hi" during the 9th

i=1
while (( i < 10))
do
    echo "Holberton School"
    if (( i == 9)); then
	echo "Hi"
    fi
    (( i++ ))
done
